# Generated by Django 6.0.3 on 2026-03-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-donation_date']},
        ),
    ]
