# Generated by Django 6.0.3 on 2026-03-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='registered_at',
            new_name='created_at',
        ),
    ]
