# Generated by Django 6.0.3 on 2026-03-30 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=3)),
                ('units', models.PositiveIntegerField()),
                ('collection_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('used', 'Used'), ('expired', 'Expired'), ('discarded', 'Discarded')], default='available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='donors.donor')),
            ],
        ),
    ]
