# Generated by Django 6.0.3 on 2026-03-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='requested_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
    ]
